- name: copy rsyslog conf file
  ansible.builtin.template:
    src: rsyslog.conf
    dest: "{{component}}.conf"

- name: restart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted