- name: Get Secrets
  hosts: local hosts
  vars:
    ssh: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=http://vault.janand.online:8200 validate_certs=False')}}"
  tasks:
    - name: Create secrets file
      ansible.builtin.fileinline:
        path: secrets.json
        line: "ansible_user: {{ ssh.user }}\nansible_password: {{ ssh.pass }}" #{{ domain_definition | community.general.json_query('user') }}"
        create: yes