- name: Get Secrets
  hosts: local hosts
  tasks:
    - name: Create a file
      ansible.builtin.fileinline:
        path: tmp/test
        line: "Username: {{ lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=http://vault.janand.online:8200 validate_certs=False')}}"
        create: yes