- name: Get Secrets
  hosts: local hosts
  tasks:
    - name: Create common secrets ssh file
      ansible.builtin.lineinfile:
        path: ~/secrets.json
        line: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=http://vault.janand.online:8200 validate_certs=False')}}"
        create: yes

    - name: create app secrete file
      ansible.builtin.lineinfile:
        path: ~/app.json
        line: "{{lookup('hashi_vault', 'secret=expense-{{env}}/data/{{ role_name }} token={{vault_token}} url=http://vault.janand.online:8200 validate_certs=False')}}"
        create: yes