format_version: 10
pipelines:
  expense-backend:
    group: defaultGroup
    label_template: "${env:APP_VERSION}"
    materials:
      git-7f8559b:
        git: https://github.com/anand-320/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:rsFNC5K8WN5aliy5fraRpQ==:NEaOhSKi7Ks9CW+vP19ih3f8aIcEKDzAn48vnkBQsvk=
    environment_variables:
      APP_VERSION: ""
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - backend
                    command: bash
                    run_if: passed
      - QA:
          fetch_materials: true
          environment_variables:
            env: qa
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - backend
                    command: bash
                    run_if: passed
      - STAGE:
          fetch_materials: true
          environment_variables:
            env: stage
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - backend
                    command: bash
                    run_if: passed
      - PROD:
          fetch_materials: true
          environment_variables:
            env: prod
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - backend
                    command: bash
                    run_if: passed